language: python
python: 
    - "3.6"
install: "pip install -r requirements.txt"
script:
- mkdir -p $HOME/.keras/
- touch $HOME/.keras/keras.json
- echo "{    \"image_data_format\": \"channels_last\",    \"epsilon\": 1e-07,    \"floatx\": \"float32\",    \"backend\": \"theano\"}" > $HOME/.keras/keras.json
- python -m unittest -v
